name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: somnath910/statuscode1:latest  # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull somnath910/statuscode1:latest  # Replace with your Docker Hub username and repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull somnath910/statuscode1:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d --name web-app \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e PORT=${{ secrets.PORT }} \
              -e SECRET=${{ secrets.SECRET }} \
              -e BREVO_USER=${{ secrets.BREVO_USER }} \
              -e BREVO_PASSWORD=${{ secrets.BREVO_PASSWORD }} \
              -e BREVO_HOST=${{ secrets.BREVO_HOST }} \
              -e BREVO_PORT=${{ secrets.BREVO_PORT }} \
              -p 3005:3000 \
              somnath910/statuscode1:latest
