name: Fetch Issue Details

on:
  issue_comment:
    types: [created]

jobs:
  fetch_issue_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: sudo apt-get install gh

      - name: Fetch issue details
        id: fetch_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
        run: |
          # Extract issue number, even if there's additional text after it
          if [[ "${{ github.event.comment.body }}" =~ ^#([0-9]+) ]]; then
            ISSUE_NUMBER="${BASH_REMATCH[1]}"  # Capture the issue number
            echo "Fetching issue #$ISSUE_NUMBER"
            
            # Fetch the issue data
            ISSUE_DATA=$(gh issue view $ISSUE_NUMBER --json title,state,body --jq '.')
            echo "ISSUE_DATA=$ISSUE_DATA" >> $GITHUB_ENV
          else
            echo "No valid issue reference found in comment."
            exit 0

      - name: Output issue data
        run: |
          echo "Issue details fetched:"
          echo "${{ env.ISSUE_DATA }}"
