name: Fetch Issue Details

on:
  issue_comment:
    types: [created]

jobs:
  fetch_issue_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch issue details
        id: fetch_issue
        run: |
          if [[ "${{ github.event.comment.body }}" =~ ^#[0-9]+$ ]]; then
            ISSUE_NUMBER="${{ github.event.comment.body }}"  # Get the entire comment
            ISSUE_NUMBER=${ISSUE_NUMBER:1}  # Remove the leading '#'
            echo "Fetching issue #$ISSUE_NUMBER"
            ISSUE_DATA=$(gh issue view $ISSUE_NUMBER --json title,state,body --jq '.')
            echo "ISSUE_DATA=$ISSUE_DATA" >> $GITHUB_ENV
          else
            echo "No valid issue reference found in comment."
            exit 0
          fi

      - name: Add comment with issue details
        if: env.ISSUE_DATA != ''
        run: |
          TITLE=$(echo $ISSUE_DATA | jq -r '.title')
          STATE=$(echo $ISSUE_DATA | jq -r '.state')
          BODY=$(echo $ISSUE_DATA | jq -r '.body')

          COMMENT="### Issue Details\n\n**Title:** $TITLE\n**State:** $STATE\n**Description:** $BODY"
          echo "Adding comment with issue details..."
          gh issue comment ${{ github.event.issue.number }} --body "$COMMENT"
